// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buisxqfpcyfofbsffzvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aXN4cWZwY3lmb2Zic2ZmenZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjYwMTIsImV4cCI6MjA2MTE0MjAxMn0.2-wVjSewDpRLlBp5sPjHcmsWtIPa_mP4N8-OaHhF1_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);